data:
  url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv
  raw_dir: artifacts/raw
  processed_dir: artifacts/processed
  test_size: 0.2
  target: median_house_value

model:
  model_dir: artifacts/model
  model_name: model.pkl

metrics:
  metrics_dir: artifacts/metrics
  reports_dir: artifacts/reports

mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: housing-price

s3:
  bucket: mlops-housing-model
  model_key: model/model.pkl
