data:
  url: https://raw.githubusercontent.com/ageron/handson-ml/master/datasets/housing/housing.csv
  raw_dir: artifacts/raw
  processed_dir: artifacts/processed
  test_size: 0.2
  target: median_house_value

model:
  model_dir: artifacts/model
  model_name: model.pkl

  candidates:
    LinearRegression:
      fit_intercept: true

    RandomForest:
      n_estimators: 251
      max_depth: 11
      random_state: 42

    GradientBoosting:
      n_estimators: 181
      learning_rate: 0.05
      max_depth: 3
      random_state: 42

metrics:
  metrics_dir: artifacts/metrics
  reports_dir: artifacts/reports

mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: housing-price

s3:
  bucket: housingmk
  model_key: model/model.pkl
